import { useEffect, useMemo, useState } from 'react';
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, Github, Linkedin, Mail, Moon, Sun } from 'lucide-react';
import { aboutCopy, certifications, education, experience, highlights, heroIntro, navLinks, projects, seminars, socials, techStacks } from './data';
import { MagneticButton, Reveal } from './components';

const featuredSkills = ['React.js', 'Flutter', 'TypeScript', 'Vue.js', 'Figma', 'Node.js', 'PostgreSQL', 'Tailwind CSS'];
type FormState = { name: string; email: string; message: string };
const initialForm: FormState = { name: '', email: '', message: '' };
function SectionTitle({ number, eyebrow, title, description }: { number: string; eyebrow: string; title: string; description?: string }) {
  return <div className="section-title"><div className="section-title-meta"><span>{number} / 08</span><span>{eyebrow}</span></div><div><h2>{title}</h2>{description && <p>{description}</p>}</div></div>;
}
function BrowserPreview({ kind = 0 }: { kind?: number }) {
  return <div className={`browser-preview preview-${kind}`} aria-hidden="true"><div className="browser-bar"><div className="browser-dots"><i/><i/><i/></div><span>{['oscaflow.app / dashboard', 'itso.nu-dasmariñas.edu / tracker', 'beautiverse.digi / shop'][kind]}</span><span>+</span></div>
    {kind === 0 ? <div className="preview-inner osca-ui"><div className="preview-side"><b>OSCA<span>Flow</span></b><small>OVERVIEW</small><em>Dashboard</em><small>OPERATIONS</small><em>Records</em><em>Applications</em><em>Reports</em></div><div className="preview-main"><small>MONDAY, MAY 12</small><h4>Good morning, Admin.</h4><p>Here's your operations overview.</p><div className="preview-stats"><div><small>APPLICATIONS</small><strong>1,284</strong><span>↗ 12.8%</span></div><div><small>FOR REVIEW</small><strong>048</strong><span>New records</span></div></div><div className="preview-chart"><small>Monthly activity</small><div className="chart-bars">{[34,52,43,68,57,83,70,91,73,100,86,95].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div></div></div></div> : kind === 1 ? <div className="preview-inner tracker-ui"><div className="tracker-head"><strong>NUD <span>ITSO</span></strong><span>Appointments & ID Tracking</span></div><div className="tracker-body"><div className="tracker-progress"><small>TRACK YOUR ID</small><h4>Every step, in view.</h4><div className="tracker-steps"><span className="done">01<br/>Booked</span><span className="done">02<br/>Verified</span><span>03<br/>Printing</span><span>04<br/>Ready</span></div></div><div className="tracker-list"><small>UPCOMING APPOINTMENTS</small><p><b>12</b><span>May<br/>Monday</span><em>Photo capture<br/><small>10:30 AM</small></em></p><p><b>16</b><span>May<br/>Friday</span><em>ID release<br/><small>2:00 PM</small></em></p></div></div></div> : <div className="preview-inner beauty-ui"><div className="beauty-head"><span>BEAUTIVERSE</span><small>DISCOVER &nbsp; SHOP &nbsp; ABOUT</small><span>♡ &nbsp; ◇</span></div><div className="beauty-body"><small>THE EVERYDAY EDIT</small><h4>Beauty in<br/><i>every detail.</i></h4><p>Thoughtfully curated essentials<br/>for your daily ritual.</p><span className="beauty-link">EXPLORE COLLECTION →</span><div className="beauty-product"><div className="beauty-bottle"/><small>SKINCARE / 01</small></div></div></div>}
  </div>;
}
function Showcase() {
  const [active, setActive] = useState(0);
  return <div className="showcase" aria-label="Interactive project showcase"><div className="showcase-top"><span>01 — SELECTED INTERFACES</span><span>INTERACTIVE PREVIEW ↗</span></div><div className="showcase-stage"><div className="showcase-grid" aria-hidden="true"/><div className="showcase-browser"><BrowserPreview kind={active}/></div><div className="showcase-phone" aria-hidden="true"><div className="phone-speaker"/><span className="phone-brand">{active === 0 ? 'OSCAFlow' : active === 1 ? 'NUD ITSO' : 'BeautiVerse'}</span><div className="phone-orb">{active === 0 ? 'OCR' : active === 1 ? 'ID' : 'B'}</div><small>{active === 0 ? 'Document scan complete' : active === 1 ? 'Your ID is on its way' : 'Discover your ritual'}</small><div className="phone-lines"><i/><i/><i/></div><div className="phone-action">{active === 0 ? 'View record' : active === 1 ? 'Track progress' : 'Explore'}</div></div><div className="showcase-code" aria-hidden="true"><div><i/><i/><i/><span>app.tsx</span></div><code><span>const</span> build = <em>{'{'}</em><br/> &nbsp; craft: <b>'purpose'</b>,<br/> &nbsp; detail: <b>'everywhere'</b><br/><em>{'}'}</em>;</code></div><span className="showcase-corner">DESIGN / DEVELOP / DELIVER</span></div><div className="showcase-bottom"><div><b>{projects[active].title}</b><span>{projects[active].role}</span></div><div className="showcase-controls" aria-label="Choose project preview">{projects.map((project, i)=><button key={project.title} type="button" className={active===i?'active':''} onClick={()=>setActive(i)} aria-label={`Show ${project.title} preview`} aria-pressed={active===i}>{String(i+1).padStart(2,'0')}</button>)}</div></div><div className="showcase-facts"><p><span>FOCUS</span><b>Mobile & web applications</b></p><p><span>CURRENTLY</span><b>BSIT · Mobile and Web Applications</b></p></div></div>;
}
function ProjectFeature({ project, index }: { project: typeof projects[number]; index: number }) {
  return <Reveal><article className={`project-feature ${index % 2 ? 'reverse' : ''}`}><div className="project-copy"><div className="project-kicker"><span>0{index+1}</span><span>FEATURED PROJECT</span></div><h3>{project.title}</h3>{project.subtitle && <p className="project-subtitle">{project.subtitle}</p>}<p className="project-role">{project.role}</p><ul>{project.details.map(detail=><li key={detail}>{detail}</li>)}</ul><div className="project-tags">{project.stack.map(item=><span key={item}>{item}</span>)}</div></div><div className="project-visual"><span className="visual-label">{index === 0 ? 'OPERATIONS / MOBILE + WEB' : index === 1 ? 'APPOINTMENTS / TRACKING' : 'WEB / SECURITY'}</span><BrowserPreview kind={index}/><div className="visual-index">0{index+1}<span>/ 03</span></div></div></article></Reveal>;
}
function App() {
  const [theme, setTheme] = useState<'light' | 'dark'>(() => document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light');
  const [menuOpen, setMenuOpen] = useState(false);
  const [form, setForm] = useState<FormState>(initialForm);
  const [status, setStatus] = useState<'idle' | 'sent'>('idle');
  const mailtoHref = useMemo(() => {
    const subject = encodeURIComponent(`Portfolio inquiry from ${form.name || 'a visitor'}`);
    const body = encodeURIComponent(`Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`);
    return `mailto:hello@katecristensantos.com?subject=${subject}&body=${body}`;
  }, [form.email, form.message, form.name]);
  const handleChange = (field: keyof FormState) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setForm(current => ({ ...current, [field]: event.target.value }));
    setStatus('idle');
  };
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    window.location.href = mailtoHref;
    setStatus('sent');
  };
  const reducedMotion = useReducedMotion();
  const { scrollYProgress } = useScroll();
  const heroShift = useTransform(scrollYProgress, [0, 0.18], [0, reducedMotion ? 0 : -42]);
  useEffect(() => { document.documentElement.dataset.theme = theme; document.querySelector('meta[name="theme-color"]')?.setAttribute('content', theme === 'dark' ? '#181616' : '#FAF8F6'); }, [theme]);
  const toggleTheme = () => setTheme(current => { const next = current === 'light' ? 'dark' : 'light'; try { localStorage.setItem('portfolio-theme', next); } catch { /* unavailable */ } return next; });
  return <div className="site-shell"><motion.div className="reading-progress" style={{scaleX:scrollYProgress}}/><header className="site-header"><div className="header-inner"><a className="brand" href="#hero" aria-label="Kate Cristen Santos, back to top"><span className="brand-mark">K<span>.</span></span><span className="brand-name">KATE CRISTEN SANTOS<small>DEVELOPER / PROJECT LEADER</small></span></a><nav className={menuOpen?'nav-links open':'nav-links'} aria-label="Primary">{navLinks.map(link=><a key={link.href} href={link.href} onClick={()=>setMenuOpen(false)}>{link.label}</a>)}</nav><div className="header-actions"><button className="theme-button" type="button" onClick={toggleTheme} aria-label={`Switch to ${theme==='light'?'dark':'light'} mode`} aria-pressed={theme==='dark'}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><a className="header-contact" href="#contact">LET'S TALK <ArrowUpRight size={15}/></a><button className="menu-button" type="button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen}>{menuOpen?'CLOSE':'MENU'}</button></div></div></header><main>
    <section id="hero" className="hero section-wrap"><div className="hero-intro"><span className="eyebrow"><span className="eyebrow-line"/> MOBILE & WEB DEVELOPER</span><h1><span>Kate</span><span>Cristen</span><span className="hero-last">Santos<span className="hero-period">.</span></span></h1><p className="hero-description">{heroIntro}</p><div className="hero-actions"><MagneticButton href="#projects" className="editorial-button" icon={<ArrowUpRight size={17}/>}>View projects</MagneticButton><MagneticButton href="#contact" variant="secondary" className="editorial-button secondary" icon={<ArrowRight size={17}/>}>Get in touch</MagneticButton></div><a className="resume-link" href="/resume.pdf" target="_blank" rel="noopener noreferrer">View / download resume <ArrowUpRight size={15} aria-hidden="true"/></a><div className="hero-scroll"><ArrowDown size={14}/><span>SCROLL TO EXPLORE</span></div></div><motion.div className="hero-visual" style={{y:heroShift}}><Showcase/></motion.div><div className="hero-footer"><span>BASED IN THE PHILIPPINES</span><span>WEB · MOBILE · LEADERSHIP</span><span>PORTFOLIO / {new Date().getFullYear()}</span></div></section>
    <section id="about" className="section-wrap content-section about-section"><div className="ambient-word" aria-hidden="true">ABOUT</div><Reveal><SectionTitle number="01" eyebrow="PROFESSIONAL SUMMARY" title={'Curious by nature.\nIntentional by design.'} description={aboutCopy}/></Reveal><div className="about-grid"><Reveal><div className="about-statement"><p>I am a BSIT student specializing in Mobile and Web Applications. Through academic and organizational projects, I have developed practical experience in web and mobile development, project management, and technical leadership.</p><p>I collaborate with software teams, manage project tasks, and contribute to system design, testing, and implementation.</p></div></Reveal><Reveal delay={0.08}><div className="about-aside"><span className="micro-label">WHAT I BRING TO THE TABLE</span><div className="about-list">{['Mobile applications','Web applications','Project coordination','UI/UX design'].map((item,i)=><div key={item}><span>0{i+1}</span><strong>{item}</strong><ArrowUpRight size={16}/></div>)}</div><p>I work with frontend and backend technologies, databases, and development tools to turn project requirements into working features.</p><p>Hands-on experience building academic applications with modern tools. Planning tasks, supporting development, and coordinating team progress.</p></div></Reveal></div><div className="metrics-strip">{highlights.map(item=><div key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></section>
    <section id="tech-stack" className="content-section skills-section"><div className="section-wrap"><Reveal><SectionTitle number="02" eyebrow="SKILLS & TOOLS" title={'A toolkit built\nfor making things work.'}/></Reveal></div><div className="marquee" aria-label="Featured technologies"><div className="marquee-track">{[...featuredSkills,...featuredSkills].map((skill,i)=><span key={`${skill}-${i}`}>{skill}<i>✳</i></span>)}</div></div><div className="section-wrap skills-grid">{techStacks.map((group,index)=><Reveal key={group.category} delay={Math.min(index*.04,.2)}><div className="skill-group"><div className="skill-heading"><span>0{index+1}</span><h3>{group.category}</h3></div><div className="skill-items">{group.items.map(item=><span key={item}>{item}</span>)}</div></div></Reveal>)}</div></section>
    <section id="projects" className="section-wrap content-section projects-section"><div className="ambient-word" aria-hidden="true">WORK</div><Reveal><SectionTitle number="03" eyebrow="SELECTED WORK" title={'Made with purpose.\nBuilt with people.'} description="Applications developed with teams across mobile, web, and security coursework."/></Reveal><div className="projects-list">{projects.map((project,index)=><ProjectFeature key={project.title} project={project} index={index}/>)}</div></section>
    <section id="experience" className="content-section experience-section"><div className="section-wrap"><Reveal><SectionTitle number="04" eyebrow="LEADERSHIP & ORGANIZATION EXPERIENCE" title={'Leading the work\nbehind the work.'}/></Reveal><div className="experience-grid"><Reveal><div className="experience-intro"><span className="micro-label">HOW I CONTRIBUTE</span>{['Coordinate team tasks and project schedules','Maintain organizational records and announcements','Plan technology events and participant logistics','Support communication across officers and members'].map((item,i)=><div key={item}><span>0{i+1}</span><p>{item}</p></div>)}</div></Reveal><div className="timeline">{experience.map((entry,index)=><Reveal key={`${entry.year}-${entry.title}`} delay={index*.05}><article className="timeline-entry"><span>{entry.year}</span><div><h3>{entry.title}</h3><p className="timeline-org">{entry.organization}</p><ul>{entry.details.map(detail=><li key={detail}>{detail}</li>)}</ul></div></article></Reveal>)}</div></div></div></section>
    <section id="education" className="section-wrap content-section education-section"><Reveal><SectionTitle number="05" eyebrow="EDUCATION" title={'Always learning.\nAlways building.'}/></Reveal><div className="education-list">{education.map((entry,index)=><Reveal key={entry.school} delay={index*.06}><article><span className="education-number">0{index+1}</span><div><p className="micro-label">{entry.period}</p><h3>{entry.school}</h3><p>{entry.program}</p><p className="muted">{entry.detail}</p></div><ArrowUpRight size={22}/></article></Reveal>)}</div><Reveal><div className="award-line"><span>✳</span><div><p className="micro-label">AWARDS & ACHIEVEMENTS</p><h3>Consistent Dean’s Lister</h3><p>National University – Dasmariñas · First Honors every term except 1st Year, 1st Term (Second Honors).</p></div></div></Reveal></section>
    <section id="certifications" className="section-wrap content-section credentials-section"><Reveal><SectionTitle number="06" eyebrow="CERTIFICATIONS" title="Validated skills."/></Reveal><div className="credentials-list">{certifications.map((cert,index)=><Reveal key={cert.name} delay={index*.06}><article><span>0{index+1}</span><div><h3>{cert.name}</h3><p>{cert.organization}</p></div><ArrowUpRight size={21}/></article></Reveal>)}</div></section>
    <section id="seminars" className="section-wrap content-section seminars-section"><Reveal><SectionTitle number="07" eyebrow="TRAINING & SEMINARS" title={'Ideas worth\nstaying curious about.'}/></Reveal><div className="seminar-list">{seminars.map((seminar,index)=><Reveal key={seminar.name} delay={Math.min(index*.025,.15)}><article><span className="seminar-index">{String(index+1).padStart(2,'0')}</span><div><h3>{seminar.name}</h3><p>{seminar.organizer}</p></div><span className="seminar-date">{seminar.date}</span></article></Reveal>)}</div></section>
    <section id="contact" className="contact-section"><div className="section-wrap"><Reveal><div className="contact-top"><span className="eyebrow">08 / CONTACT</span><span>HAVE SOMETHING IN MIND?</span></div><h2>Let's make<br/><em>something</em> happen<span>.</span></h2><p>Reach out about development projects, collaborations, or opportunities.</p><a className="contact-email" href={socials[2].href}>Open email <ArrowUpRight size={23}/></a><form className="contact-form" onSubmit={handleSubmit}>
  <div className="contact-form-heading"><span className="micro-label">SEND A MESSAGE</span><span>DIRECT INQUIRY</span></div>
  <div className="contact-form-row">
    <label><span>Name</span><input name="name" value={form.name} onChange={handleChange('name')} placeholder="Your name" autoComplete="name" /></label>
    <label><span>Email</span><input name="email" type="email" value={form.email} onChange={handleChange('email')} placeholder="Your email" autoComplete="email" /></label>
  </div>
  <label className="contact-message"><span>Message</span><textarea name="message" value={form.message} onChange={handleChange('message')} placeholder="Tell me about your project or collaboration idea" /></label>
  <div className="contact-form-action"><button type="submit">Send message <ArrowUpRight size={18} aria-hidden="true"/></button><p role="status">{status === 'sent' ? 'Your email client is opening.' : 'This form opens a prefilled email draft for quick contact.'}</p></div>
</form><div className="contact-bottom"><div><span className="micro-label">SOCIAL LINKS</span><div className="social-links"><a href={socials[0].href} target="_blank" rel="noreferrer"><Github size={18}/> GitHub <ArrowUpRight size={14}/></a><a href={socials[1].href} target="_blank" rel="noreferrer"><Linkedin size={18}/> LinkedIn <ArrowUpRight size={14}/></a><a href={socials[2].href}><Mail size={18}/> Email <ArrowUpRight size={14}/></a></div></div><div className="collab-note"><span className="micro-label">OPEN TO COLLABORATION</span><p>I enjoy working with teams on mobile and web applications, from planning through implementation.</p></div></div></Reveal></div></section>
  </main><footer className="site-footer"><div className="section-wrap"><span>© {new Date().getFullYear()} KATE CRISTEN SANTOS</span><a href="#hero">BACK TO TOP ↑</a><span>DESIGNED & BUILT WITH INTENTION</span></div></footer></div>;
}
export default App;
